vote:
  app: vote
  replica: 1
  image:
    container_name: vote
    repo: ajmaldocker07/vote_app
    tag: 6
  service:
    port: 5000
    targetport: 80

result:
  app: result
  replica: 1
  image:
    container_name: result
    repo: ajmaldocker07/result_app
    tag: 6
  service:
    port: 5001
    targetport: 80

    

